#!/usr/bin/env python
# coding=utf-8
#
# simple git update for set pulling from core modules
#
import os
import sys



# check where we are and load default directory
if os.path.isdir("/usr/local/share/setoolkit-pt"):
    if not os.path.isfile("se-toolkit"):
        os.chdir("/usr/local/share/setoolkit-pt")
        sys.path.append("/usr/local/share/setoolkit-pt")

import src.core.setcore as core

# if we can't see our config then something didn't go good..
if not os.path.isfile("/etc/setoolkit-pt/set.config"):
    core.print_error("Não foi possível localizar o executável do SET. Tente executar a partir do diretório local.")
    core.print_error("Se isso não funcionar, por favor, execute o arquivo setup.py install.")
    sys.exit()

try:
    # pull update set from the core libraries
    core.update_set()

# except keyboard interrupts
except KeyboardInterrupt:
    print("\n[!] Control-C detetado. Saindo da atualização do SET.")

# handle all other errors
except Exception as e:
    print("\n[!] Algo deu errado.. Printing the error: {0}".format(e))
